name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: xcodebuild -target Fomalhaut2Tests -scheme Fomalhaut2 test
