name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      id: cache
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Fomalhaut2.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: resolve packages
      run: xcodebuild -resolvePackageDependencies -clonedSourcePackagesDirPath .build
      if: steps.cache.outputs.cache-hit != 'true'
    - name: test
      run: |
        cp Fomalhaut2Tests/fixture/empty.zip Fomalhaut2/assets.zip
        set -o pipefail && xcodebuild -target Fomalhaut2Tests -scheme Fomalhaut2 -clonedSourcePackagesDirPath .build DEVELOPMENT_TEAM= clean test | xcpretty
