name: web
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: yarn install
        run: yarn install
        working-directory: ./web
      - name: "install @jamesacarr/eslint-formatter-github-actions"
        run: yarn add -D @jamesacarr/eslint-formatter-github-actions
      - name: Lint
        run: yarn lint
        working-directory: ./web
        env:
          NPM_CONFIG_ESLINT_ARGS: "-f @jamesacarr/github-actions"
