name: web
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./web

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: pnpm install
        run: pnpm install
      - name: Lint
        run: pnpm run lint
        env:
          ESLINT_ARGS: "-f @jamesacarr/github-actions"
